app:
  name: TeleTrix CRM System
  debug: true

database:
  engine: postgresql
  host: localhost
  port: 5432
  name: crm_db
  user: db_user
  # password: db_password  # Пароль лучше через переменные окружения

telegram_bot:
  token_env_var: TELEGRAM_BOT_TOKEN # Имя переменной окружения, где хранится токен пользователя

admin_telegram_bot:
  token_env_var: ADMIN_TELEGRAM_BOT_TOKEN # Имя переменной окружения, где хранится токен администратора

logging:
  level: DEBUG
  format: '%(asctime)s - %(levelname)s - %(message)s'

#types of storadges: file | database
storage_type: file
storage:
  file: 
    path: storage/  # Путь к папке хранения файлов
    data_file_type: yaml  # Тип файла для хранения данных: yaml | json
    categories: categories
    products: products
    users: users
  database:
    engine: postgresql
    host: localhost
    port: 5432
    name: teletrix_db
    user: super_user
    password: storage_password  # Пароль лучше через переменные окружения