app:
  name: TeleTrix CRM System
  debug: true
telegram:
  bot:
    admin:
      token_env_var: ADMIN_TB_TOKEN
    customer:
      token_env_var: CUSTOMER_TB_TOKEN
storage:
  file: 
    path: storage/  # Path to folder where files are stored
    data_file_type: yaml  # Тип файла для хранения данных: yaml | json
    categories: categories
    products: products
    users: users
    orders: orders
    order_items: order_items
  database:
    engine: postgresql
    url: localhost
    port: 5432
    name: teletrix_db
    user: super_user
    password: storage_password  # Пароль лучше через переменные окружения