-
  name: Product 1
  photo: https://images.uzum.uz/cpc7ptvfrr82f0a4na10/original.jpg
  decsription: Description of product 1
  quantity: 10
  price: 1000
  category: Category 1
-
  name: Product 2
  photo: https://images.uzum.uz/cpc7ptvfrr82f0a4na10/original.jpg
  decsription: Description of product 2
  quantity: 20
  price: 2000
  category: Category 2
-
  name: Product 3
  photo: https://images.uzum.uz/cpc7ptvfrr82f0a4na10/original.jpg
  decsription: Description of product 3
  quantity: 30
  price: 3000
  category: Category 3